cache:
  - C:\strawberry

install:
  - if not exist "C:\strawberry" cinst strawberryperl
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - cpanm --installdeps .

build_script:
  - del t\eintr.t
  - del t\signal.t
  - del t\timeout.t
  - del t\timer.t
  - perl Makefile.PL
  - prove -bv

branches:
  except:
    - /travis/
skip_tags: true
